/*============================================
                  CONTENT
============================================*/
const Content = {
  fruit: [
    ["strawberry", "match1"],
    ["strawberry", "match1"],
    ["lemon", "match2"],
    ["lemon", "match2"],
    ["grapes", "match3"],
    ["grapes", "match3"],
    ["cherries", "match4"],
    ["cherries", "match4"],
    ["pear", "match5"],
    ["pear", "match5"],
    ["peach","match6" ],
    ["peach","match6" ],
    ["apple", "match7"],
    ["apple", "match7"],
    ["orange", "match8"],
    ["orange", "match8"]
  ],
  animals: [
    ["bird", "match1"],
    ["bird", "match1"],
    ["elephant", "match2"],
    ["elephant", "match2"],
    ["tiger", "match3"],
    ["tiger", "match3"],
    ["lion", "match4"],
    ["lion", "match4"],
    ["monkey", "match5"],
    ["monkey", "match5"],
    ["turkey","match6" ],
    ["turkey","match6" ],
    ["eagle", "match7"],
    ["eagle", "match7"],
    ["zebra", "match8"],
    ["zebra", "match8"]
  ],
  spanish: [
    ["hello", "match1"],
    ["hola", "match1"],
    ["goodbye", "match2"],
    ["adios", "match2"],
    ["grapes", "match3"],
    ["uvas", "match3"],
    ["horse", "match4"],
    ["caballo", "match4"],
    ["car", "match5"],
    ["carro", "match5"],
    ["house","match6" ],
    ["casa","match6" ],
    ["apple", "match7"],
    ["manzana", "match7"],
    ["table", "match8"],
    ["mesa", "match8"]
  ],
  fruit_pics: [
    ["<img src='./images/strawberry.svg' />", "match1"],
    ["<img src='./images/strawberry.svg' />", "match1"],
    ["<img src='./images/lemon.svg' />", "match2"],
    ["<img src='./images/lemon.svg' />", "match2"],
    ["<img src='./images/grapes.svg' />", "match3"],
    ["<img src='./images/grapes.svg' />", "match3"],
    ["<img src='./images/cherries.svg' />", "match4"],
    ["<img src='./images/cherries.svg' />", "match4"],
    ["<img src='./images/pear.svg' />", "match5"],
    ["<img src='./images/pear.svg' />", "match5"],
    ["<img src='./images/peach.svg' />","match6" ],
    ["<img src='./images/peach.svg' />","match6" ],
    ["<img src='./images/apple.svg' />", "match7"],
    ["<img src='./images/apple.svg' />", "match7"],
    ["<img src='./images/orange.svg' />", "match8"],
    ["<img src='./images/orange.svg' />", "match8"]
  ],
  als_pics: [
    ["actor", "match1"],
    ["<img class='sign-lang-img' src='./images/asl_pics/actor.gif' />", "match1"],
    ["artist", "match2"],
    ["<img class='sign-lang-img' src='./images/asl_pics/artist.gif' />", "match2"],
    ["ball", "match3"],
    ["<img class='sign-lang-img' src='./images/asl_pics/ball.gif' />", "match3"],
    ["deaf", "match4"],
    ["<img class='sign-lang-img' src='./images/asl_pics/deaf.gif' />", "match4"],
    ["basketball", "match5"],
    ["<img class='sign-lang-img' src='./images/asl_pics/basketball.gif' />", "match5"],
    ["talk","match6" ],
    ["<img class='sign-lang-img' src='./images/asl_pics/talk.gif' />","match6" ],
    ["music", "match7"],
    ["<img class='sign-lang-img' src='./images/asl_pics/music.gif' />", "match7"],
    ["play", "match8"],
    ["<img class='sign-lang-img' src='./images/asl_pics/play.gif' />", "match8"]
  ],
  animal_sounds: [
    ["cow", "match1"],
    ["<img id='cow' src='./images/audio_file.svg' />", "match1"],
    ["duck", "match2"],
    ["<img id='duck' src='./images/audio_file.svg' />", "match2"],
    ["elephant", "match3"],
    ["<img id='elephant' src='./images/audio_file.svg' />", "match3"],
    ["goat", "match4"],
    ["<img id='goat' src='./images/audio_file.svg' />", "match4"],
    ["dog", "match5"],
    ["<img id='dog' src='./images/audio_file.svg' />", "match5"],
    ["horse","match6"],
    ["<img id='horse' src='./images/audio_file.svg' />","match6" ],
    ["frog", "match7"],
    ["<img id='frog' src='./images/audio_file.svg' />", "match7"],
    ["sheep", "match8"],
    ["<img id='sheep' src='./images/audio_file.svg' />", "match8"]
  ],
  animalPics_sounds: [
    ["<img src='./images/animal_pics/cow.svg' />", "match1"],
    ["<img id='cow' src='./images/audio_file.svg' />", "match1"],
    ["<img src='./images/animal_pics/duck.svg' />", "match2"],
    ["<img id='duck' src='./images/audio_file.svg' />", "match2"],
    ["<img src='./images/animal_pics/elephant.svg' />", "match3"],
    ["<img id='elephant' src='./images/audio_file.svg' />", "match3"],
    ["<img src='./images/animal_pics/frog.svg' />", "match4"],
    ["<img id='frog' src='./images/audio_file.svg' />", "match4"],
    ["<img src='./images/animal_pics/chicken.svg' />", "match5"],
    ["<img id='chicken' src='./images/audio_file.svg' />", "match5"],
    ["<img src='./images/animal_pics/horse.svg' />","match6"],
    ["<img id='horse' src='./images/audio_file.svg' />","match6" ],
    ["<img src='./images/animal_pics/dog.svg' />", "match7"],
    ["<img id='dog' src='./images/audio_file.svg' />", "match7"],
    ["<img src='./images/animal_pics/sheep.svg' />", "match8"],
    ["<img id='sheep' src='./images/audio_file.svg' />", "match8"]
  ],
};
