/*============================================
                  CONTENT
============================================*/
export const content = {
  fruit: [
    ["strawberry", "match1"],
    ["strawberry", "match1"],
    ["lemon", "match2"],
    ["lemon", "match2"],
    ["grapes", "match3"],
    ["grapes", "match3"],
    ["cherries", "match4"],
    ["cherries", "match4"],
    ["pear", "match5"],
    ["pear", "match5"],
    ["peach","match6" ],
    ["peach","match6" ],
    ["apple", "match7"],
    ["apple", "match7"],
    ["orange", "match8"],
    ["orange", "match8"]
  ],
  animals: [
    ["bird", "match1"],
    ["bird", "match1"],
    ["elephant", "match2"],
    ["elephant", "match2"],
    ["tiger", "match3"],
    ["tiger", "match3"],
    ["lion", "match4"],
    ["lion", "match4"],
    ["monkey", "match5"],
    ["monkey", "match5"],
    ["turkey","match6" ],
    ["turkey","match6" ],
    ["eagle", "match7"],
    ["eagle", "match7"],
    ["zebra", "match8"],
    ["zebra", "match8"]
  ],
  spanish: [
    ["hello", "match1"],
    ["hola", "match1"],
    ["goodbye", "match2"],
    ["adios", "match2"],
    ["grapes", "match3"],
    ["uvas", "match3"],
    ["horse", "match4"],
    ["caballo", "match4"],
    ["car", "match5"],
    ["carro", "match5"],
    ["house","match6" ],
    ["casa","match6" ],
    ["apple", "match7"],
    ["manzana", "match7"],
    ["table", "match8"],
    ["mesa", "match8"]
  ],
  fruit_pics: [
    ["<img src='./images/strawberry.svg' />", "match1"],
    ["<img src='./images/strawberry.svg' />", "match1"],
    ["<img src='./images/lemon.svg' />", "match2"],
    ["<img src='./images/lemon.svg' />", "match2"],
    ["<img src='./images/grapes.svg' />", "match3"],
    ["<img src='./images/grapes.svg' />", "match3"],
    ["<img src='./images/cherries.svg' />", "match4"],
    ["<img src='./images/cherries.svg' />", "match4"],
    ["<img src='./images/pear.svg' />", "match5"],
    ["<img src='./images/pear.svg' />", "match5"],
    ["<img src='./images/peach.svg' />","match6" ],
    ["<img src='./images/peach.svg' />","match6" ],
    ["<img src='./images/apple.svg' />", "match7"],
    ["<img src='./images/apple.svg' />", "match7"],
    ["<img src='./images/orange.svg' />", "match8"],
    ["<img src='./images/orange.svg' />", "match8"]
  ]
};
